### ISSUE TITLE
Destruction of messsageboard fails

### ISSUE THREAD

**Issue by fosterfarrell9** [thredded/thredded#860]
It appears that the destruction of messageboards (either directly via messageboard.destroy or via the gui as introduced in #825) does not work:

```
NoMethodError (undefined method `update_last_user_and_time_from_last_post!' for nil:NilClass):

thredded (0.16.16) app/models/thredded/post.rb:81:in `update_parent_last_user_and_time_from_last_post'

```
The reason seems to be that the callbacks are triggered in an order that destroys topics before posts, resulting in postables that are `nil`. Adding safe navigation to postable seems to fix the problem.
