### PR TITLE
fix assets:precompile with assets.compile = false 

### LINKED ISSUE #1010: Exception with assets:precompile in v1.2.0 (on test/staging)
```
export RAILS_ENV=test
bundle exec rake assets:precompile assets:clean

NoMethodError: undefined method `preprocessors' for nil:NilClass

      if !Rails.env.production? && app.assets.preprocessors.keys.exclude?('text/scss')
                                             ^^^^^^^^^^^^^^
/home/circleci/.../vendor/bundle/ruby/3.1.0/gems/thredded-1.2.0/lib/thredded/engine.rb:25:in `block in <class:Engine>'
```

### PR DESCRIPTION
**Pull request by timdiggins**
fixes #1010

### CODE REVIEW

**Review by glebm — APPROVED** [review]

File: spec/dummy/config/environments/test.rb [hunk 1]
```diff
@@ -1,6 +1,12 @@
 # frozen_string_literal: true
 
 Dummy::Application.configure do
+  config.assets.compile = if ENV['PRECOMPILE_ASSETS']
+                            false
+                          else
+                            true
+                          end
+
```
Comment (glebm) [inline spec/dummy/config/environments/test.rb:9]:
```suggestion
  config.assets.compile = !ENV['PRECOMPILE_ASSETS']
```
