### ISSUE TITLE
Exception with assets:precompile in v1.2.0 (on test/staging)

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#1010]
```
export RAILS_ENV=test
bundle exec rake assets:precompile assets:clean

NoMethodError: undefined method `preprocessors' for nil:NilClass

      if !Rails.env.production? && app.assets.preprocessors.keys.exclude?('text/scss')
                                             ^^^^^^^^^^^^^^
/home/circleci/.../vendor/bundle/ruby/3.1.0/gems/thredded-1.2.0/lib/thredded/engine.rb:25:in `block in <class:Engine>'
```

**Comment by timdiggins** [comment]
So if you use `config.assets.compile = false` somewhere not in production (e.g. in test, staging) and you're doing `rails assets:precompile` or similar then the assets will be `nil`. So we could make this conditional on assets being present.

**Comment by timdiggins** [comment]
![Image](https://github.com/user-attachments/assets/4dac2434-b791-43e1-b59b-3db670ec469b)
https://github.com/thredded/thredded/actions/runs/15342103252/job/43170248041
